AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
Style/FormatStringToken:
  Enabled: false
Style/FormatString:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
