name: Scrape latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Fetch latest data
      run: bundle exec ruby get-appointments --appointments 7
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    - name: Commit and push if appointment data changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Generate web page
      run: bundle exec ruby get-appointments --make-appointment-list
    - name: Commit and push if html changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Generate index.html ${timestamp}" || exit 0
        git push
