name: Scrape latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/New_York
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Fetch latest data
      run: bundle exec ruby get-appointments --appointments 21 --force
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        DEBUG_LOG: ${{ secrets.DEBUG_LOG }}
    - name: Commit and push if appointment data changed
      run: |-
        if ! git diff --quiet; then
          bundle exec ruby get-appointments --make-appointment-list
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
        fi
